### ISSUE TITLE
vite config conflict

### ISSUE THREAD

**Issue by efturtle** [mehmetsagir/v-svg-icons#3]
This vue component has the file inclusion without the ending of .vue
![image](https://user-images.githubusercontent.com/46721097/176725878-eef4dd16-266b-4c8d-a47d-27f76f9db2ae.png)

With vite setup there is conflict on the import as these files have to be ending with .vue

This is the error I get
![image](https://user-images.githubusercontent.com/46721097/176726170-9a3042e2-3e9d-406c-95b9-298b4d3387ef.png)

when updated to .vue the conflict disappears, as shown here 
![image](https://user-images.githubusercontent.com/46721097/176726442-3dfef504-92df-4bb3-9a87-6371fdfb4667.png)

Was wondering if there could be a flag setup on the install of this package so it could switch it in case someone is using the vite config. Or any other ideas on this?

**Comment by mehmetsagir** [comment]
Hello, if you look at it, I am thinking of updating the structure completely at the first opportunity. I will post more icons with a neater structure. I did not encounter the error you mentioned before, I will pay attention to this error after the update. Thank you

**Comment by efturtle** [comment]
Oh and heads up for spam also tagged you on Twitter lol

**Comment by mehmetsagir** [comment]
I fixed the error and released a new version so that it does not interfere with use. You can continue to use it by installing version 1.1.5

**Comment by efturtle** [comment]
Awesome, thanks!
